import { IMultiCentralV1Dto } from './entity.schema.types';

export const multiCentralsV1Fixtures: Array<IMultiCentralV1Dto> = [
  {
    id: 1,
    instituicao_id: 1,
    unidade_id: 1,
    departamento_id: 1,
    nome: 'Fake Central 1',
    sigla: 'FC1',
    site: 'http://www.c.uni.com/fc1',
    email: 'fc1@fake.uni.br',
    telefone1: '(00) 0000-0000',
    telefone2: '(00) 0000-0000',
    endereco_id: 1,
    como_chegar: null,
    sobre:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.',
    horario_atendimento: 'Monday to Friday, from 8:00 to 18:00',
    observacoes:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.',
    tesouraria: false,
    passo_atual: 6,
    central_status_id: 5,
    foto_arquivo_id: 19,
    created: '2020-09-15T23:08:51.893Z',
    created_by: 1,
    updated: '2023-11-09T14:33:29.055Z',
    updated_by: 456,
    deleted: null,
    instituicao: {
      id: 1,
      nome: 'Fake University',
      sigla: 'FU',
      documento_institucional: 'FU Number',
      link_numero_patrimonio: 'https://fake-link-numero-patrimonio-1.com',
    },
    unidade: { id: 64, instituicao_id: 1, nome: 'Fake Center', sigla: 'FC' },
    departamento: {
      id: 2510,
      instituicao_id: 1,
      unidade_id: 64,
      nome: 'Fake Department',
    },
    foto: {
      id: 19,
      nome_original: 'x3u9e4yl98lncexmcsti8zkmjo1k0hg4.jpg',
      nome_final: 'x3u9e4yl98lncexmcsti8zkmjo1k0hg4.jpg',
      path: 'public/images/x3u9e4yl98lncexmcsti8zkmjo1k0hg4.jpg',
      encoding: '7bit',
      mimetype: 'image/jpeg',
      tamanho: 1374669,
    },
    endereco: {
      id: 63,
      internacional: false,
      cep: '00000-000',
      logradouro: 'Fake Avenue',
      numero: '303',
      complemento: 'Fake Complement',
      bairro: 'Fake Neighborhood',
      cidade: 'Fake City',
      estado: 'SP',
      pais: 'Brasil',
    },
  },
];
