/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface IMultiCentralV1Dto {
  /**
   * The unique identifier of a multi central as an integer
   */
  id: number;
  /**
   * The unique identifier of a multi institution as an integer
   */
  instituicao_id: number;
  /**
   * The unique identifier of the unit that the multi central belongs to as an integer
   */
  unidade_id: number;
  departamento_id?: null | number;
  /**
   * The name of the multi central
   */
  nome: string;
  /**
   * The acronym of the multi central
   */
  sigla: string;
  site?: null | string;
  /**
   * The email of the multi central
   */
  email: string;
  /**
   * The first phone number of the multi central
   */
  telefone1: string;
  telefone2?: null | string;
  endereco_id?: null | number;
  como_chegar?: null | string;
  sobre?: null | string;
  horario_atendimento?: null | string;
  observacoes?: null | string;
  /**
   * The flag that indicates if the multi central is a treasury
   */
  tesouraria: boolean;
  /**
   * The current step of the multi central as an integer
   */
  passo_atual: number;
  /**
   * The unique identifier of the status of the multi central as an integer
   */
  central_status_id: number;
  foto_arquivo_id?: null | number;
  /**
   * The creation date of the multi central
   */
  created: string;
  /**
   * The unique identifier of the user that created the multi central as an integer
   */
  created_by: number;
  /**
   * The last update date of the multi central
   */
  updated: string;
  /**
   * The unique identifier of the user that updated the multi central as an integer
   */
  updated_by: number;
  deleted?: null;
  instituicao?: IMultiInstitutionV1Dto;
  unidade?: IMultiUnitV1Dto;
  departamento?: null | IMultiDepartmentV1Dto;
  foto?: null | {
    /**
     * The unique identifier of the photo as an integer
     */
    id: number;
    /**
     * The original name of the photo
     */
    nome_original: string;
    /**
     * The final name of the photo
     */
    nome_final: string;
    /**
     * The path of the photo
     */
    path: string;
    /**
     * The encoding of the photo
     */
    encoding: "7bit";
    /**
     * The mimetype of the photo
     */
    mimetype: "image/jpeg" | "image/png";
    /**
     * The size of the photo as an integer
     */
    tamanho: number;
    [k: string]: unknown;
  };
  endereco?: null | {
    /**
     * The unique identifier of the address as an integer
     */
    id: number;
    /**
     * The flag that indicates if the address is international
     */
    internacional: boolean;
    /**
     * The postal code of the address
     */
    cep: string;
    /**
     * The street of the address
     */
    logradouro: string;
    /**
     * The number of the address
     */
    numero: string;
    complemento?: null | string;
    /**
     * The neighborhood of the address
     */
    bairro: string;
    /**
     * The city of the address
     */
    cidade: string;
    /**
     * The state of the address
     */
    estado: string;
    /**
     * The country of the address
     */
    pais: string;
    [k: string]: unknown;
  };
}
export interface IMultiInstitutionV1Dto {
  /**
   * The unique identifier of a multi institution as an integer
   */
  id: number;
  /**
   * The name of the multi institution
   */
  nome: string;
  /**
   * The acronym of the multi institution
   */
  sigla: string;
  documento_institucional?: null | string;
  link_numero_patrimonio?: null | string;
}
export interface IMultiUnitV1Dto {
  /**
   * The unique identifier of the unit as an integer
   */
  id: number;
  /**
   * The unique identifier of the institution that the unit belongs to as an integer
   */
  instituicao_id: number;
  /**
   * The name of the unit
   */
  nome: string;
  /**
   * The acronym of the unit
   */
  sigla: string;
}
export interface IMultiDepartmentV1Dto {
  /**
   * The unique identifier of the department as an integer
   */
  id: number;
  /**
   * The unique identifier of the institution that the department belongs to as an integer
   */
  instituicao_id: number;
  /**
   * The unique identifier of the unit that the department belongs to as an integer
   */
  unidade_id: number;
  /**
   * The name of the department
   */
  nome: string;
}
