/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { JSONSchema7 } from "json-schema";

export type CoreSchemaMetaSchema = JSONSchema7;
/**
 * @minItems 1
 */
export type SchemaArray = [CoreSchemaMetaSchema, ...CoreSchemaMetaSchema[]];
export type StringArray = string[];

export interface ICreateFirstVersionOfTaxonomicUnitV1InputDto {
  name: string;
  instanceSchema: CoreSchemaMetaSchema;
  metadataSchema: CoreSchemaMetaSchema;
  metadata:
  | null
  | {
    [k: string]: unknown;
  }
  | unknown[]
  | string
  | number
  | boolean;
  /**
   * The unique identifier of the parent taxonomic unit, as a hexadecimal string of 24 characters. If the value is null, the taxon is the root of a taxonomic hierarchy
   */
  parentId: string | null;
}
