version: '3.8'

volumes:
  zookeeper:
    driver: local

  kafka:
    driver: local

  confluent-control-center:
    driver: local

  postgres:
    driver: local

  mongodb:
    driver: local

  # hasura:
  #   driver: local

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    hostname: zookeeper
    container_name: zookeeper
    volumes:
      - zookeeper:/var/lib/zookeeper/data
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-server:7.3.0
    hostname: kafka
    container_name: kafka
    volumes:
      - kafka:/var/lib/kafka/data
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
      - '9094:9094'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092,OUTSIDE://host.docker.internal:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CONFLUENT_METRICS_ENABLE: 'false'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

  confluent-control-center:
    image: confluentinc/cp-enterprise-control-center:7.3.0
    hostname: control-center
    container_name: confluent-control-center
    volumes:
      - confluent-control-center:/var/lib/confluent-control-center/data
    depends_on:
      - kafka
    ports:
      - '9021:9021'
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:29092'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021

  postgres:
    image: postgres:12
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: always
    environment:
      - POSTGRES_USER=local-postgres-user
      - POSTGRES_PASSWORD=local-postgres-password

  # Mongo Database container initialization (https://hub.docker.com/r/mongodb/mongodb-community-server/tags)
  mongodb:
    image: mongodb/mongodb-community-server:7.0.9-ubi8
    restart: always
    container_name: mongodb
    volumes:
      - mongodb:/var/lib/mongodb/data
    ports:
      - '27017:27017'
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=local-root-user
      - MONGODB_INITDB_ROOT_PASSWORD=local-root-password
    deploy:
      resources:
        limits:
          cpus: '0.2564' # (0.2439 -> 4100 MHz, 0.2564 -> 3900 Mhz)
          memory: '1024MB'

  things-assets-catalog-rest-api:
    image: node:18.17.1
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 8080:8080
    command: 'dist/apps/things/assets-catalog/rest-api/main.js'
    depends_on:
      - mongodb
      # - kafka
    env_file:
      - dist/apps/things/assets-catalog/rest-api/.env
    deploy:
      resources:
        limits:
          cpus: '0.2564' # (0.2439 -> 4100 MHz, 0.2564 -> 3900 Mhz)
          memory: '512MB'

  prometheus:
    image: prom/prometheus:v2.47.0
    command:
      - --web.enable-remote-write-receiver
      - --enable-feature=native-histograms
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana:10.1.2
    ports:
      - '3000:3000'
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/

  # # Mongo Express (https://github.com/mongo-express/mongo-express)
  # mongo-express:
  #   depends_on:
  #     - mongo
  #   image: mongo-express
  #   container_name: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   env_file:
  #     - .env

  # hasura:
  #   image: hasura/graphql-engine:v2.18.0
  #   container_name: hasura
  #   volumes:
  #     - hasura:/var/lib/hasura/data
  #   ports:
  #     - '8080:8080'
  #   depends_on:
  #     - 'postgres'
  #   restart: always
  #   env_file:
  #     - .env
