/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ISeedOrganizationsFromExternalSourceInputDto {
  /**
   * A string that identifies the source where organizations should be extracted from
   */
  sourceName: "USP_MULTI";
  /**
   * The unique identifier of an agent as a hexadecimal string of 28 characters.
   */
  agentAccountHolderId: string;
}
