/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ITaxonomicUnitInstanceV1 {
  /**
   * The unique identifier of a taxonomic unit as a hexadecimal string of 24 characters.
   */
  id: string;
  schema: {
    version: number;
    name: string;
  };
  data: {
    [k: string]: unknown;
  };
}
