/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface IGetOrganizationsV1UrlQueryParams {
  /**
   * The page number. It must be an integer greater than or equal to 1 and less than or equal to 4294967295.
   */
  page?: string;
  /**
   * The number of items per page. It must be greater than or equal to 1 and less than or equal to 100.
   */
  limit?: string;
  /**
   * The unique identifier of an agent as a hexadecimal string of 28 characters.
   */
  ownerAgentId?: string;
  [k: string]: unknown;
}
