/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { JSONSchema7 } from 'json-schema';

export type CoreSchemaMetaSchema = JSONSchema7;
/**
 * @minItems 1
 */
export type SchemaArray = [CoreSchemaMetaSchema, ...CoreSchemaMetaSchema[]];
export type StringArray = string[];
/**
 * Filtered Taxonomic Units V1
 */
export type IFilteredTaxonomicUnitV1List = ITaxonomicUnitV1[];

export interface ITaxonomicUnitV1 {
  /**
   * The unique identifier of a taxonomic unit as a hexadecimal string of 24 characters.
   */
  id: string;
  version: number;
  name: string;
  /**
   * The taxonomic lineage of a taxon (taxonomic unit) from the root to the taxon itself, as represented by a path of ids in the hierarchy
   */
  lineageIdPath: string;
  metadata:
  | null
  | {
    [k: string]: unknown;
  }
  | unknown[]
  | string
  | number
  | boolean;
  metadataSchema: CoreSchemaMetaSchema;
  instanceSchema: CoreSchemaMetaSchema;
}
