/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type IJsonSchemaMetaSchemaV7 = {
  $id?: string;
  $schema?: string;
  $ref?: string;
  $comment?: string;
  title?: string;
  description?: string;
  default?: unknown;
  readOnly?: boolean;
  writeOnly?: boolean;
  examples?: unknown[];
  multipleOf?: number;
  maximum?: number;
  exclusiveMaximum?: number;
  minimum?: number;
  exclusiveMinimum?: number;
  maxLength?: NonNegativeInteger;
  minLength?: NonNegativeIntegerDefault0;
  pattern?: string;
  additionalItems?: IJsonSchemaMetaSchemaV7;
  items?: IJsonSchemaMetaSchemaV7 | SchemaArray;
  maxItems?: NonNegativeInteger;
  minItems?: NonNegativeIntegerDefault0;
  uniqueItems?: boolean;
  contains?: IJsonSchemaMetaSchemaV7;
  maxProperties?: NonNegativeInteger;
  minProperties?: NonNegativeIntegerDefault0;
  required?: StringArray;
  additionalProperties?: IJsonSchemaMetaSchemaV7;
  definitions?: {
    [k: string]: IJsonSchemaMetaSchemaV7;
  };
  properties?: {
    [k: string]: IJsonSchemaMetaSchemaV7;
  };
  patternProperties?: {
    [k: string]: IJsonSchemaMetaSchemaV7;
  };
  dependencies?: {
    [k: string]: IJsonSchemaMetaSchemaV7 | StringArray;
  };
  propertyNames?: IJsonSchemaMetaSchemaV7;
  const?: unknown;
  /**
   * @minItems 1
   */
  enum?: [unknown, ...unknown[]];
  type?: SimpleTypes | [SimpleTypes, ...SimpleTypes[]];
  format?: string;
  contentMediaType?: string;
  contentEncoding?: string;
  if?: IJsonSchemaMetaSchemaV7;
  then?: IJsonSchemaMetaSchemaV7;
  else?: IJsonSchemaMetaSchemaV7;
  allOf?: SchemaArray;
  anyOf?: SchemaArray;
  oneOf?: SchemaArray;
  not?: IJsonSchemaMetaSchemaV7;
  [k: string]: unknown;
} & (
  | {
      $id?: string;
      $schema?: string;
      $ref?: string;
      $comment?: string;
      title?: string;
      description?: string;
      default?: unknown;
      readOnly?: boolean;
      writeOnly?: boolean;
      examples?: unknown[];
      multipleOf?: number;
      maximum?: number;
      exclusiveMaximum?: number;
      minimum?: number;
      exclusiveMinimum?: number;
      maxLength?: NonNegativeInteger;
      minLength?: NonNegativeIntegerDefault0;
      pattern?: string;
      additionalItems?: IJsonSchemaMetaSchemaV7;
      items?: IJsonSchemaMetaSchemaV7 | SchemaArray;
      maxItems?: NonNegativeInteger;
      minItems?: NonNegativeIntegerDefault0;
      uniqueItems?: boolean;
      contains?: IJsonSchemaMetaSchemaV7;
      maxProperties?: NonNegativeInteger;
      minProperties?: NonNegativeIntegerDefault0;
      required?: StringArray;
      additionalProperties?: IJsonSchemaMetaSchemaV7;
      definitions?: {
        [k: string]: IJsonSchemaMetaSchemaV7;
      };
      properties?: {
        [k: string]: IJsonSchemaMetaSchemaV7;
      };
      patternProperties?: {
        [k: string]: IJsonSchemaMetaSchemaV7;
      };
      dependencies?: {
        [k: string]: IJsonSchemaMetaSchemaV7 | StringArray;
      };
      propertyNames?: IJsonSchemaMetaSchemaV7;
      const?: unknown;
      /**
       * @minItems 1
       */
      enum?: [unknown, ...unknown[]];
      type?: SimpleTypes | [SimpleTypes, ...SimpleTypes[]];
      format?: string;
      contentMediaType?: string;
      contentEncoding?: string;
      if?: IJsonSchemaMetaSchemaV7;
      then?: IJsonSchemaMetaSchemaV7;
      else?: IJsonSchemaMetaSchemaV7;
      allOf?: SchemaArray;
      anyOf?: SchemaArray;
      oneOf?: SchemaArray;
      not?: IJsonSchemaMetaSchemaV7;
      [k: string]: unknown;
    }
  | boolean
);
export type NonNegativeInteger = number;
export type NonNegativeIntegerDefault0 = NonNegativeInteger;
/**
 * @minItems 1
 */
export type SchemaArray = [IJsonSchemaMetaSchemaV7, ...IJsonSchemaMetaSchemaV7[]];
export type StringArray = string[];
export type SimpleTypes = "array" | "boolean" | "integer" | "null" | "number" | "object" | "string";
