/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface IMultiInstitutionV1Dto {
  /**
   * The unique identifier of a multi institution as an integer
   */
  id: number;
  /**
   * The name of the multi institution
   */
  nome: string;
  /**
   * The acronym of the multi institution
   */
  sigla: string;
  documento_institucional?: null | string;
  link_numero_patrimonio?: null | string;
}
