/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { JSONSchema7 } from "json-schema";

export type CoreSchemaMetaSchema = JSONSchema7;
/**
 * @minItems 1
 */
export type SchemaArray = [CoreSchemaMetaSchema, ...CoreSchemaMetaSchema[]];
export type StringArray = string[];

export interface ITaxonomicUnitInstanceV1 {
  /**
   * The unique identifier of a taxonomic unit as a hexadecimal string of 24 characters.
   */
  id: string;
  schema: {
    version: number;
    name: string;
  };
  data: CoreSchemaMetaSchema;
}
