/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { JSONSchema7 } from "json-schema";

export type CoreSchemaMetaSchema = JSONSchema7;
/**
 * @minItems 1
 */
export type SchemaArray = [CoreSchemaMetaSchema, ...CoreSchemaMetaSchema[]];
export type StringArray = string[];

export interface ICreateTaxonomicUnitV1InstanceInputDto {
  schema: {
    version: number;
    name: string;
  };
  data: unknown;
}
