/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PositiveInteger = number;
export type PositiveIntegerDefault0 = PositiveInteger;
/**
 * @minItems 1
 */
export type SchemaArray = [IJsonSchemaMetaSchemaV4, ...IJsonSchemaMetaSchemaV4[]];
/**
 * @minItems 1
 */
export type StringArray = [string, ...string[]];
export type SimpleTypes = "array" | "boolean" | "integer" | "null" | "number" | "object" | "string";

/**
 * Core schema meta-schema v4
 */
export interface IJsonSchemaMetaSchemaV4 {
  id?: string;
  $schema?: string;
  title?: string;
  description?: string;
  default?: unknown;
  multipleOf?: number;
  maximum?: number;
  exclusiveMaximum?: boolean;
  minimum?: number;
  exclusiveMinimum?: boolean;
  maxLength?: PositiveInteger;
  minLength?: PositiveIntegerDefault0;
  pattern?: string;
  additionalItems?: boolean | IJsonSchemaMetaSchemaV4;
  items?: IJsonSchemaMetaSchemaV4 | SchemaArray;
  maxItems?: PositiveInteger;
  minItems?: PositiveIntegerDefault0;
  uniqueItems?: boolean;
  maxProperties?: PositiveInteger;
  minProperties?: PositiveIntegerDefault0;
  required?: StringArray;
  additionalProperties?: boolean | IJsonSchemaMetaSchemaV4;
  definitions?: {
    [k: string]: IJsonSchemaMetaSchemaV4;
  };
  properties?: {
    [k: string]: IJsonSchemaMetaSchemaV4;
  };
  patternProperties?: {
    [k: string]: IJsonSchemaMetaSchemaV4;
  };
  dependencies?: {
    [k: string]: IJsonSchemaMetaSchemaV4 | StringArray;
  };
  /**
   * @minItems 1
   */
  enum?: [unknown, ...unknown[]];
  type?: SimpleTypes | [SimpleTypes, ...SimpleTypes[]];
  format?: string;
  allOf?: SchemaArray;
  anyOf?: SchemaArray;
  oneOf?: SchemaArray;
  not?: IJsonSchemaMetaSchemaV4;
  [k: string]: unknown;
}
