/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PositiveInteger = number;
export type PositiveIntegerDefault0 = PositiveInteger;
/**
 * @minItems 1
 */
export type SchemaArray = [JsonSchemaV4MetaSchema, ...JsonSchemaV4MetaSchema[]];
/**
 * @minItems 1
 */
export type StringArray = [string, ...string[]];
export type SimpleTypes = "array" | "boolean" | "integer" | "null" | "number" | "object" | "string";

/**
 * Core schema meta-schema
 */
export interface JsonSchemaV4MetaSchema {
  id?: string;
  $schema?: string;
  title?: string;
  description?: string;
  default?: unknown;
  multipleOf?: number;
  maximum?: number;
  exclusiveMaximum?: boolean;
  minimum?: number;
  exclusiveMinimum?: boolean;
  maxLength?: PositiveInteger;
  minLength?: PositiveIntegerDefault0;
  pattern?: string;
  additionalItems?: boolean | JsonSchemaV4MetaSchema;
  items?: JsonSchemaV4MetaSchema | SchemaArray;
  maxItems?: PositiveInteger;
  minItems?: PositiveIntegerDefault0;
  uniqueItems?: boolean;
  maxProperties?: PositiveInteger;
  minProperties?: PositiveIntegerDefault0;
  required?: StringArray;
  additionalProperties?: boolean | JsonSchemaV4MetaSchema;
  definitions?: {
    [k: string]: JsonSchemaV4MetaSchema;
  };
  properties?: {
    [k: string]: JsonSchemaV4MetaSchema;
  };
  patternProperties?: {
    [k: string]: JsonSchemaV4MetaSchema;
  };
  dependencies?: {
    [k: string]: JsonSchemaV4MetaSchema | StringArray;
  };
  /**
   * @minItems 1
   */
  enum?: [unknown, ...unknown[]];
  type?: SimpleTypes | [SimpleTypes, ...SimpleTypes[]];
  format?: string;
  allOf?: SchemaArray;
  anyOf?: SchemaArray;
  oneOf?: SchemaArray;
  not?: JsonSchemaV4MetaSchema;
  [k: string]: unknown;
}
