/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ITaxonomicUnitV1Dto {
  /**
   * The unique identifier of an agent as a hexadecimal string of 24 characters.
   */
  id: string;
  /**
   * The slug of the taxonomic unit. It must have at least 4 characters.
   */
  slug: string;
  /**
   * The date and time when the agent was created.
   */
  createdAt: string;
  /**
   * The date and time when the agent was last updated.
   */
  updatedAt: string;
}
