/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface IMultiDepartmentV1Dto {
  /**
   * The unique identifier of the department as an integer
   */
  id: number;
  /**
   * The unique identifier of the institution that the department belongs to as an integer
   */
  instituicao_id: number;
  /**
   * The unique identifier of the unit that the department belongs to as an integer
   */
  unidade_id: number;
  /**
   * The name of the department
   */
  nome: string;
}
