/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface IOrganizationV1DtoSchema {
  /**
   * The unique identifier of an agent as a hexadecimal string of 24 characters.
   */
  id: string;
  /**
   * The nickname of the agent. It must have at least 4 characters.
   */
  nickname: string;
  /**
   * The email of the organization. An organization agent can have the same e-mail of its owner only if its owner is an individual agent. Two organizations cannot have the same e-mail.
   */
  email: string;
  /**
   * The unique identifier of an agent as a hexadecimal string of 28 characters.
   */
  agentId: string;
  /**
   * The unique identifier of the agent that owns the organization, as a hexadecimal string of 28 characters.
   */
  ownerAgentId: string;
  /**
   * The type of the agent. It can be individual or organization.
   */
  planSubscriptionName: "FREE";
  /**
   * The path of the organization in the hierarchy.
   */
  idPath: string;
  /**
   * The date and time when the agent was created.
   */
  createdAt: string;
  /**
   * The date and time when the agent was last updated.
   */
  updatedAt: string;
}
